const baseConfig = require('../.eslintrc.cjs')

module.exports = (program) => ({
    ...baseConfig,
    parserOptions: {
        ...baseConfig.parserOptions,
        programs: [program], // replace eslint typescript program
    },
    // ignore non-ts virtual files that was generated by volar
    ignorePatterns: ['**/*.html', '**/*.pug', '**/*.css', '**/*.scss'],
    overrides: [
        ...baseConfig.overrides ?? [],
        {
            // ignore invalid errors for volar code
            files: ['*.vue.ts', '*.vue.js', '*.vue.tsx', '*.vue.jsx'],
            rules: {
                'prettier/prettier': 'off',
            },
        },
    ],
})
